# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\"\x1d\n\x0cHelloRequest\x12\r\n\x05value\x18\x01 \x01(\x05\"\x1b\n\nHelloReply\x12\r\n\x05value\x18\x01 \x01(\x05\x32/\n\x07Greeter\x12$\n\x06\x44ouble\x12\r.HelloRequest\x1a\x0b.HelloReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=14
  _HELLOREQUEST._serialized_end=43
  _HELLOREPLY._serialized_start=45
  _HELLOREPLY._serialized_end=72
  _GREETER._serialized_start=74
  _GREETER._serialized_end=121
# @@protoc_insertion_point(module_scope)
